import:
  - display/desktop/xsetroot
  - display/desktop/feh
  - display/color/zenburn
  - display/client
  - display/tags
  - display/status/notice
  - display/status/weather
  - display/status/arrange
  - display/status/pomodoro
  - display/status/music/mpd
  - display/status/volume
  #- display/status/network
  #- display/status/disk
  - display/status/load
  #- display/status/memory
  - display/status/power
  - display/status/time
  - control/mouse
  - control/keyboard/dvorak
  - control/keyboard/dvorak/arrange_by_number
  - control/keyboard/dvorak/client
  - control/keyboard/dvorak/detach
  - control/keyboard/dvorak/focus_by_letter
  - control/keyboard/dvorak/focus_by_number
  - control/keyboard/dvorak/focus
  - control/keyboard/dvorak/group
  - control/keyboard/dvorak/launch
  - control/keyboard/dvorak/layout_by_number
  - control/keyboard/dvorak/layout
  - control/keyboard/dvorak/menu
  - control/keyboard/dvorak/move_by_number
  - control/keyboard/dvorak/move
  - control/keyboard/dvorak/swap_by_number
  - control/keyboard/dvorak/swap
  - control/keyboard/dvorak/zoom

prefer:
  terminal: urxvt
  browser: chromium
  editor: gvim
  filer: thunar

display:
  bar: top
  font: "xft:Sans-10"
  border: 1
  column:
    mode: default
    rule: |
      /gimp/ -> 17+83+41
      /chat/ -> 17+83+41
      /.*/ -> 50+50
  client:
    rule: |
      /^pcmanfm:/ group=0
      /^firefox:/ group=0

      /^chromium:/ group=0 continue=1
      /^chromium:Chromium:Task Manager/ floating=on
      /^chromium:Chromium:Chromium Preferences$/ floating=on

      /^claws-mail:Claws-mail:Claws Mail [0-9]+\./ tags=mail
      /^claws-mail:/ floating=on

      /^sonata:/ tags=1 allow=+activate

      /^skype:|^Pidgin:/ tags=chat allow=+activate

      /^zim:/ tags=note

      /^rdesktop:/ tags=doze floating=on

      /^xwrits:/ tags=/./

      /^gimp:/ tags=gimp

      /Thunar:File Operation Progress/ floating=on

      /^vncviewer:/ floating=on
      /^alsaplayer:/ floating=on
      /:MPlayer:/ floating=on
      /^xmessage:/ floating=on tags=/./
      /^xmag:/ floating=on
      /^arandr:/ floating=on
      /^wicd-client/ floating=on
      /^pinentry/ floating=on
      /^tkmidity/ floating=on
      /^<nil>:<nil>:Event Tester$/ floating=on # xev

  status:
    arrange:
      @choices:
        right_stack: |
          tile_right
          managed_areas.last.layout = :stack
    time:
      @format: "%a %b %d, %R"
      refresh: 30
    volume:
      @mixer: Master
    disk:
      @path: $HOME
    network:
      instances:
        - @interface: wlan0
        - @interface: eth0
          refresh: 60
    weather:
      @location: SJC
    notice:
      control:
        action:
          show_desktop: focus_view '...'
        mouse_action:
          right_click: show_desktop
          wheel_up: focus_next_view
          wheel_down: focus_previous_view

script:
  - after: |
      # relaunch every time to accomodate changes in screen resolution
      launch 'witray'

control:
  action:
    desktop: | # dock laptop to my desk
      system 'xrandr --output HDMI1 --auto --output LVDS1 --off --dpi 96'
      system 'xset dpms force on' # wake up monitor from power saving mode
      system 'setxkbmap us -option ""'
      system 'marble-mouse left'
      action 'reload' # reposition witray & update shortcuts to new xkbmap

    laptop: | # undock laptop from my desk
      system 'xrandr --output LVDS1 --auto --output HDMI1 --off --output VGA1 --off --dpi 96'
      system 'setxkbmap dvorak -option ""'
      system 'mpc pause'
      action 'reload' # reposition witray & update shortcuts to new xkbmap

    projector: | # display through a projector
      system 'xrandr --output VGA1 --auto --output LVDS1 --off --dpi 96'
      system 'xset dpms force on' # wake up monitor from power saving mode

    autotop: | # recover from bad xrandr
      system 'xrandr --auto --dpi 96'
      system 'xset dpms force on' # wake up monitor from power saving mode

    portrait: | # rotate screen vertically
      system 'xrandr -o left && xrandr --dpi 96'

    landscape: | # rotate screen horizontally
      system 'xrandr -o normal && xrandr --dpi 96'

    suspend: | # put laptop to sleep
      action 'laptop'
      launch 'xlock' # password protection
      system 'sudo /etc/rc.d/networkmanager stop'
      system 'sudo pm-suspend'
      system 'sudo /etc/rc.d/networkmanager start'
